fbitvect.x:  fbitvect.o bitvect.o
	g++ -std=c++11 -Wall -Wextra -o fbitvect.x fbitvect.o bitvect.o

fbitvect.o: fbitvect.cpp
	g++ -std=c++11 -Wall -Wextra -c -I. fbitvect.cpp

bitvect.o: bitvect.cpp
	g++ -std=c++11 -Wall -Wextra -c -I. bitvect.cpp